apiVersion: apps/v1
kind: Deployment
metadata:
  name: reminder-worker
  namespace: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reminder-worker
  template:
    metadata:
      labels:
        app: reminder-worker
    spec:
      containers:
        - name: reminder-worker
          image: localhost:32000/todo-reminder-worker:ci-32
          imagePullPolicy: Always
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: todo-config
                  key: NODE_ENV

            - name: RABBITMQ_URL
              valueFrom:
                configMapKeyRef:
                  name: todo-config
                  key: RABBITMQ_URL

            - name: REMINDER_QUEUE
              valueFrom:
                configMapKeyRef:
                  name: todo-config
                  key: REMINDER_QUEUE

            - name: NOTIFICATION_FUNCTION_URL
              valueFrom:
                configMapKeyRef:
                  name: todo-config
                  key: NOTIFICATION_FUNCTION_URL

            - name: NOTIFICATION_FUNCTION_HOST_HEADER
              valueFrom:
                configMapKeyRef:
                  name: todo-config
                  key: NOTIFICATION_FUNCTION_HOST_HEADER

            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: todo-secrets
                  key: MONGODB_URI

            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: todo-secrets
                  key: MONGO_URI