apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: notification-function
  namespace: todo-app
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
        autoscaling.knative.dev/max-scale: "3"
        autoscaling.knative.dev/initial-scale: "1"
    spec:
      containers:
        - image: localhost:32000/todo-notification-function:ci-21
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7000
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: todo-config
                  key: NODE_ENV