apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-config
  namespace: todo-app
data:
  NODE_ENV: "production"

  BACKEND_PORT: "5000"
  FRONTEND_PORT: "5173"

  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"
  RABBITMQ_URL: "amqp://todo:todo@rabbitmq:5672"

  REMINDER_QUEUE: "reminder.jobs"
  ATTACHMENT_QUEUE: "attachment.uploaded"

  NOTIFICATION_FUNCTION_URL: "http://kourier.kourier-system.svc.cluster.local/notify"
  NOTIFICATION_FUNCTION_HOST_HEADER: "notification-function.todo-app.192.168.27.134.sslip.io"

  MINIO_ENDPOINT: "minio"
  MINIO_PORT: "9000"
  MINIO_USE_SSL: "false"
  MINIO_BUCKET: "note-attachments"